import type { Metadata } from "next";

export const metadata: Metadata = { title: "Match Intelligence 2026 | Argentina vs Switzerland", description: "An end-to-end football prediction system: 67 years of match data, calibrated probabilities, and a computer-vision match finale." };

const metrics = [
  { name: "Accuracy", baseline: 42.24, model: 58.89 }, { name: "Balanced accuracy", baseline: 33.33, model: 49.06 }, { name: "Macro F1", baseline: 19.8, model: 43.4 }, { name: "Log loss", baseline: 1.0644, model: 0.9213 }, { name: "Brier score", baseline: 0.6457, model: 0.5423 },
];

export default function Home() { return <main>
  <nav className="nav"><a className="brand" href="#top"><span className="brandMark">MI</span><span>Match Intelligence <b>2026</b></span></a><div className="navLinks"><a href="#system">System</a><a href="#results">Results</a><a href="#vision">Vision</a></div><a className="navCta" href="#finale">Watch the finale ↓</a></nav>
  <header id="top" className="hero"><div className="heroMedia" aria-hidden="true"/><div className="heroShade"/><div className="heroContent"><p className="eyebrow"><span/> Final project · World Cup 2026</p><h1>Before the whistle.<br/><em>Know the odds.</em></h1><p className="heroDek">A transparent match prediction engine meets real-time computer vision—turning decades of football history into a story you can see unfold.</p><div className="heroActions"><a className="button primary" href="#finale">Experience the match</a><a className="button secondary" href="/final-paper.pdf">Read the paper ↗</a></div></div><div className="heroScorecard"><div><span className="flag argentina"/><small>ARGENTINA</small><strong>46.59%</strong></div><div className="versus"><span>PRE-MATCH</span><b>VS</b><span>NEUTRAL VENUE</span></div><div><span className="flag swiss"/><small>SWITZERLAND</small><strong>33.14%</strong></div><p>DRAW <b>20.28%</b></p></div><div className="scrollCue">SCROLL TO EXPLORE <i>↓</i></div></header>
  <section className="statement"><p className="kicker">THE QUESTION</p><h2>Can we predict football <em>honestly</em>—and make the uncertainty visible?</h2><p>Football resists certainty. That is the point. This system does not promise a crystal ball; it builds a reproducible probability estimate from only what would have been known before kickoff, then puts those probabilities on the match itself.</p></section>
  <section id="system" className="dataSection"><div className="sectionHead"><p className="kicker">01 · THE EVIDENCE</p><h2>67 years.<br/>One clean timeline.</h2><p>International results were unified, validated, and split chronologically to prevent tomorrow from leaking into yesterday.</p></div><div className="bigStats"><div><strong>3,961</strong><span>international matches</span></div><div><strong>24</strong><span>competitions represented</span></div><div><strong>1958—2025</strong><span>historical match window</span></div><div><strong>36</strong><span>pre-match features</span></div></div><div className="timeline"><span>1958</span><i/><b>TRAIN · 3,168 MATCHES</b><i className="test"/><b>TEST · 793</b><span>2025</span></div></section>
  <section className="pipeline"><div className="sectionHead light"><p className="kicker">02 · THE APPROACH</p><h2>From raw history<br/>to match intelligence.</h2></div><div className="steps">{[["01","COLLECT","Match history","Scores, rankings, form, venue context, and competition metadata."],["02","ENGINEER","Pre-kickoff signals","Rolling form and relative team-strength features without future leakage."],["03","TRAIN","Interpretable model","Regularized multinomial logistic regression, selected by chronological validation."],["04","CALIBRATE","Probability first","Evaluate confidence with log loss, Brier score, and reliability—not accuracy alone."],["05","VISUALIZE","See the prediction","YOLO detections and live probability graphics encoded into presentation video."]].map(s=><article key={s[0]}><b>{s[0]}</b><span>{s[1]}</span><h3>{s[2]}</h3><p>{s[3]}</p></article>)}</div></section>
  <section id="results" className="results"><div className="sectionHead"><p className="kicker">03 · THE RESULT</p><h2>A model that beats<br/>the honest baseline.</h2><p>Held-out evaluation covers the newest 20% of matches. Green is the trained model; gray is the majority-class baseline.</p></div><div className="metricGrid">{metrics.map(m=><article className="metric" key={m.name}><div><h3>{m.name}</h3><strong>{m.model<2?m.model.toFixed(4):`${m.model.toFixed(2)}%`}</strong></div><div className="bars"><span style={{width:`${m.baseline<2?m.baseline*70:m.baseline}%`}}/><i style={{width:`${m.model<2?m.model*70:m.model}%`}}/></div><small>BASELINE {m.baseline<2?m.baseline.toFixed(4):`${m.baseline.toFixed(2)}%`}</small></article>)}</div><aside className="truth"><b>THE HONEST LIMITATION</b><p>The model improves every primary held-out metric, but makes zero hard draw predictions. Temperature scaling also worsened log loss from 0.9159 to 0.9213. Those are not footnotes—they define the next research question.</p></aside></section>
  <section id="vision" className="vision"><div className="visionImage" aria-hidden="true"/><div className="visionCopy"><p className="kicker">04 · COMPUTER VISION</p><h2>The model enters<br/>the stadium.</h2><p>YOLOv8m follows people and the ball across a full 1080p broadcast. The pre-match probability engine stays on screen, making the prediction readable in context.</p><div className="visionStats"><div><strong>25,090</strong><span>people detections</span></div><div><strong>1,865</strong><span>ball detections</span></div><div><strong>59.55%</strong><span>sampled frames with ball</span></div><div><strong>13.34</strong><span>sampled FPS on M1 Pro</span></div></div></div></section>
  <section className="hardware"><p className="kicker">BUILT LOCALLY</p><h2>Serious inference.<br/>Practical hardware.</h2><p>The complete presentation pipeline ran locally on a 10-core Apple M1 Pro with 16 GB unified memory. Detection processed 1,953 sampled frames in 146.37 seconds—proof that an end-to-end sports analytics workflow does not require a data center.</p><div className="chip"><span>M1</span><b>PRO</b><small>10-CORE · 16 GB</small></div></section>
  <section id="finale" className="finale"><div className="finaleHead"><div><p className="kicker">05 · THE FINALE</p><h2>Watch the prediction<br/>meet the match.</h2></div><p>Argentina vs Switzerland · 02:10 · 1080p source<br/>Web presentation edition with embedded detections and odds.</p></div><div className="videoFrame"><video controls playsInline preload="metadata" poster="/hero.jpg"><source src="/finale-web.mp4" type="video/mp4"/>Your browser does not support embedded video.</video><div className="videoMeta"><span>● MATCH INTELLIGENCE</span><span>ARG 46.59 &nbsp; DRAW 20.28 &nbsp; SUI 33.14</span></div></div></section>
  <footer><div className="brand"><span className="brandMark">MI</span><span>Match Intelligence <b>2026</b></span></div><p>Research, model, computer vision, and presentation—built end to end.</p><a href="#top">BACK TO TOP ↑</a></footer>
</main> }
